[package]
name = "proxmox-systemd"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = """
Utilities for dealing with systemd unit files and communicating with systemd.
"""

exclude.workspace = true

[dependencies]
libc.workspace = true
