[package]
name = "proxmox-time"
version = "2.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "time utilities and TmEditor"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
lazy_static.workspace = true
nom = "7"

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
libc = { workspace = true, features = [ "extra_traits" ] }

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
