[package]
name = "proxmox-sys"
version = "0.6.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "System tools (using nix)."

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
lazy_static.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
openssl = { workspace = true, optional = true }
regex.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = [ "derive" ] }
zstd = { workspace = true, optional = true}

proxmox-io.workspace = true
proxmox-lang.workspace = true

[features]
default = []
logrotate = ["dep:zstd"]
acl = []
crypt = ["dep:openssl"]
timer = []
