[package]
name = "proxmox-apt-api-types"
version = "1.0.1"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true
description = "APT API type definitions."

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_plain.workspace = true
proxmox-schema = { workspace = true, features = ["api-macro"] }
proxmox-config-digest.workspace = true
