[package]
name = "proxmox-uuid"
version = "1.0.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "bindings for libuuid with optional serde support"

exclude.workspace = true

[dependencies]
serde = { workspace = true, optional = true }

[features]
default = []

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[target.'cfg(target_arch="wasm32")'.dependencies]
js-sys = "0.3.55"
