[package]
name = "proxmox-serde"
version = "0.1.2"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Serde formatting tools"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }

proxmox-time.workspace = true

[dev-dependencies]
serde_json.workspace = true
