[package]
name = "proxmox-worker-task"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Worker task functionality"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
