[package]
name = "proxmox-shared-memory"
description = "Shared memory helpers and shared mutex implementation"
version = "0.3.1"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
nix.workspace = true

proxmox-sys.workspace = true
