[package]
name = "proxmox-subscription"
version = "0.4.4"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Proxmox subscription utilitites"

exclude.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
hex.workspace = true
lazy_static.workspace = true
openssl.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true

proxmox-http = { workspace = true, features = ["client-trait", "http-helpers"] }
proxmox-serde.workspace = true
proxmox-sys.workspace = true
proxmox-time.workspace = true

proxmox-schema = { workspace = true, features = ["api-macro"], optional = true }

[features]
default = []
api-types = ["dep:proxmox-schema"]
