[package]
name = "proxmox-lang"
version = "1.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "simple rust language utilities such as try_block, which have no dependencies"

exclude.workspace = true

[dependencies]
