[package]
name = "proxmox-rrd"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
exclude.workspace = true
description = "Simple RRD database implementation."

[dev-dependencies]
proxmox-router = { workspace = true, features = ["cli", "server"] }

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
crossbeam-channel.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
serde.workspace = true
serde_cbor.workspace = true
serde_json.workspace = true

proxmox-schema = { workspace = true, features = [ "api-macro" ] }
proxmox-sys.workspace = true
proxmox-time.workspace = true

[features]
default = [ "rrd_v1" ]
rrd_v1 = []
