[package]
name = "proxmox-rest-server"
version = "0.5.4"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "REST server implementation"

exclude.workspace = true

[dev-dependencies]
proxmox-schema = { workspace = true, features = [ "api-macro" ] }
tokio = { workspace = true, features = [ "rt-multi-thread", "signal", "process" ] }

[dependencies]
anyhow.workspace = true
futures.workspace = true
handlebars = { workspace = true, optional = true }
http.workspace = true
hyper = { workspace = true, features = [ "full" ] }
lazy_static.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
once_cell.workspace = true
openssl.workspace = true
percent-encoding.workspace = true
regex.workspace = true
serde = { workspace = true, features = [ "derive" ] }
serde_json.workspace = true
tokio = { workspace = true, features = ["signal", "process"] }
tokio-openssl.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tower-service.workspace = true
url.workspace = true

proxmox-async.workspace = true
proxmox-compression.workspace = true
proxmox-http = { workspace = true, optional = true }
proxmox-io.workspace = true
proxmox-lang.workspace = true
proxmox-log.workspace = true
proxmox-router.workspace = true
proxmox-schema = { workspace = true, features = [ "api-macro", "upid-api-impl" ] }
proxmox-sys = { workspace = true, features = [ "logrotate", "timer" ] }
proxmox-time.workspace = true

[features]
default = []
templates = ["dep:handlebars"]
rate-limited-stream = [
    "dep:proxmox-http",
    "proxmox-http?/rate-limited-stream",
]
