[package]
name = "proxmox-product-config"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Configuration file handling for Proxmox products."

exclude.workspace = true

[dependencies]
anyhow.workspace = true
hex.workspace = true
log.workspace = true
nix.workspace = true
proxmox-sys = { workspace = true, features = ["timer"] }
